name: Setup Code
description: Setup Code

runs:
  using: composite
  steps:
    - name: copy google-services-json
      shell: bash
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode --ignore-garbage > ./app/google-services.json

    - name: copy firebase.json
      shell: bash
      run: |
        echo "${{ secrets.FIREBASE_JSON }}" | base64 --decode --ignore-garbage > ./firebase.json
