name: Build apk

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name || 'main' }}

      - name: copy google-services-json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode --ignore-garbage > ./app/google-services.json
          

      - name: Build With Gradle
        shell: bash
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      # こんなエラーが出た。なので、このステップを挟む。      
      # Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools...
      # 参考：https://github.com/r0adkll/sign-android-release/issues/84#issuecomment-1889636075
      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app  #いらないか
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 1